//! CLI command implementations.

pub mod admin;
pub mod appimage;
pub mod apply;
pub mod base;
pub mod build_info;
pub mod capture;
pub mod changelog;
pub mod completions;
pub mod containerfile;
pub mod dev;
pub mod distrobox;
pub mod dnf;
pub mod doctor;
pub mod drift;
pub mod extension;
pub mod flatpak;
pub mod gsetting;
pub mod homebrew;
pub mod local;
pub mod profile;
pub mod repo;
pub mod schema;
pub mod shim;
pub mod skel;
pub mod status;
pub mod system;
pub mod upstream;
